name: Build and Release

on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: windows-2019
    steps:
      - name: Checkout branch
        uses: actions/checkout@master
      - name: Quickbuild
        run: ./quickbuild.bat --i-agree-to-the-vendor-licenses -j 2 address-model=64 msconvert
      - name: Zip
        run: tar -czvf msconvert.tar.gz -C build-nt-x86/msvc-release-x86_64 .
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }}
          release_name: ${{ github.run_id }}
          draft: false
          prerelease: false
      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./msconvert.tar.gz
          asset_name: msconvert.tar.gz
          asset_content_type: application/gzip
